let nama = "Warda";
let umur = 19;
let tinggi = 157;
let mahasiswaAktif= true;
let alamat = "Bandung";
let nilai = 85;
let lulus = true;

console.log(nama);
console.log(umur);
console.log(tinggi);
console.log(mahasiswaAktif);
console.log(alamat);
console.log(nilai);
console.log(lulus);
console.log(typeof nama);
console.log(typeof umur);
console.log(typeof tinggi);
console.log(typeof mahasiswaAktif);
console.log(typeof alamat);
console.log(typeof nilai);
console.log(typeof lulus);